spring:
  application:
    name: notification-service



ride-booking-request:
  exchange: ride.booking.request.exchange
  queue: ride.booking.request.queue
  routing-key: ride.booking.request.key

ride-offer:
  exchange: ride.offer.exchange
  queue: ride.offer.queue
  routing-key: ride.offer.key