server:
  port: 8085
spring:
  application:
    name: ride-management-service
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    template:
      exchange: ride-exchange
  datasource:
    url: jdbc:postgresql://localhost:5432/ride_management
    username: postgres
    password: patelji
