server:
  port: 8086
spring:
  application:
    name: ride-matching-service
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  redis:
    host: localhost
    port: 6379

ride-matching:
  search-radius: 5.0 # kilometers
  max-drivers-to-consider: 5
